### ISSUE TITLE
create folders to store LR / HR seperately

### ISSUE THREAD

**Issue by leslie-wang** [MKFMIKU/RAISR#1]
seems like the codes downscale and upscale in train.py at real time. Suggest to do it offline. FFMPEG has different scaling filter. we can reuse that to generate training picture. I can give a hand if you want.

**Comment by MKFMIKU** [comment]
After have seen the code in SRCNN, I think do this in real time is possible to generate training picture.No speed need.

And thank you.

**Comment by VRdeveloperA** [comment]
This is great project, now is it support colorful picture?

**Comment by MKFMIKU** [comment]
It just need more time to let it work. 😂

**Comment by MKFMIKU** [comment]
now, we support colorful picture
