### ISSUE TITLE
some doubts about your code

### ISSUE THREAD

**Issue by luckyjie** [MKFMIKU/RAISR#2]
hi,dear author
    recently,i have read this paper,and  luckily i have found your code.but i have some question about it.
1.i guess you wrote your code in python 3.0,because i can't run it in python2.7，then i changed some codes,and succeed.
2.i have some doubts about your codes in reconstruction your low solution image.
the following are some codes of you:
` [angle,strength,coherence] = hashTable(patch,Qangle,Qstrenth,Qcoherence)
        f = H[angle,strength,coherence]
        patch = patch.reshape(1,-1)
        LRImage[jPixel,iPixel] = patch*np.matrix(f).T
        jPixel = jPixel+1`

in google's paper,after we classified our patches into buckets,there may be no patch or a little patches in buckets because there are often many more horizontal and vertical structures in imagery,and flat regions are common,but i can't see what solution you make in your paper.

为了表述更清楚，我下面使用中文（见笑）：在谷歌论文分桶的时候，有些结构经常出现有些出现得少使得桶子里面的图像块数非常少，你是怎样处理这个的？

my email is ：jxy1968@163.com
i am looking forward your reply!

**Comment by MKFMIKU** [comment]
这个问题我也没有很好的解决方案啊，其实现在测试的结果依然不是很好，不知道为什么。

I have no idea why the algorithm is not as cool as the google said, maybe I made something wrong.

**Comment by oppo62258801** [comment]
你好，在code/train.py里面line62的地方sparse.linalg.cg()，一直显示找不到cg模块，你使用的是哪个版本的，这和版本有关系吗？

**Comment by MKFMIKU** [comment]
@oppo62258801 try to update scipy into the newest version

**Comment by oppo62258801** [comment]
OK, thank you! now I have solved this problem by coding like this:
...
import scipy.sparse.linalg as splinalg
.....
h[j,t] = splinalg.cg(Q[j,t],V[j,t])[0]
.....
.
but I have annother problem. I think your code in train.py in about line 36 should be modified into:
...
#模糊LR
#Upscaling
LR = cv2.resize(mat,(0,0),fx=0.5,fy=0.5)
LR = cv2.GaussianBlur(LR,(0,0),2);
...
#Set the train map
LR = cv2.resize(LR,(0,0),fx=2,fy=2)
...
and now I have trained some images with you code,but it does not work so well for most test images, so  I am looking forward for your timely help  and I would appreciate your help!

**Comment by MKFMIKU** [comment]
Say the truth, it also not work good for me, I try to solve it.

**Comment by binerone** [comment]
hi, dear author! i am a student now, today i run this program in my computer and find it took more than 10 minutes to test, is this normal?

and in hashTable.py 
    strength = np.floor(strength/(1/Qstrenth)-1)
    coherence = np.floor(coherence/(1/Qcoherence)-1)
When running to these two sentences, will be given: cannot convert float infinity to integer.  i print the 'strength' and 'coherence' and get 'inf', i donot kown where am i wrong.

So I temporarily change these two words:
    strength = np.floor(strength*Qstrenth-1)
    coherence = np.floor(coherence*Qcoherence-1)
I know it might be wrong to do so，but i have no idea now. I hope you can help me about it. very thanks.

**Comment by MKFMIKU** [comment]
@binerone I cannot reproduce your error, but it seems like the Qcoherence get zero, you could make some break point to see what is wrong, welcome your contribution

**Comment by binerone** [comment]
@MKFMIKU i known where the problem was now. the code:
               strength = np.floor(strength/(1/Qstrenth)-1)
               coherence = np.floor(coherence/(1/Qcoherence)-1)
carry executed the floor division, not true division, where Qcoherence = 3, but 1/Qcoherence = 0.

so i added the code:
               from __future__ import division
in hashTable.py, than that problem solved.than i get 1/Qcoherence = 0.333333333, and there is no erro now. but it still takes almost 10min.
hope this can help other friends.

**Comment by MKFMIKU** [comment]
FIx
