### ISSUE TITLE
and integer or boolean arrays are valid indices

### ISSUE THREAD

**Issue by EstebanExplorer** [MKFMIKU/RAISR#3]
Hi friend, thanks for the project,

I know that your time is valuable, but I would appreciate it too much if you could guide me,

I am trying to run the file train.py in python 3.5, it shows me the following error:
File "train.py", line 57, in <module>
    Q[angle,strength,coherence] = Q[angle,strength,coherence] + patch.T*patch
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Beforehand thank you very much,

Greetings from Colombia

Excuse my English I use the google translator

**Comment by MKFMIKU** [comment]
I have update the code, but the works not so good.

**Comment by EstebanExplorer** [comment]
Thanks friend for the answer

**Comment by calidoso** [comment]
MKVMIKU, para mi trabajo el nuevo repo es perfecto,asi mismo pude descubrir porque fallaba el anterior repo.

solo faltaba retornar como valores enteros la funcion hashTable en el fichero hashTable.py

nuevament muchas gracias por el repo y por tomarte el tiempo de responderme.

saludos

**Comment by EstebanExplorer** [comment]
MKVMIKU, for my work the new repo is perfect, so I was able to discover why the previous repo failed.

Only needed to return as a whole the hashTable function in the file hashTable.py

Again thank you very much for the repo and for taking the time to respond.

regards

**Comment by MKFMIKU** [comment]
OK~
