### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BenjaminWegener** [MKFMIKU/RAISR#4]
Traceback (most recent call last):
  File "train.py", line 44, in <module>
    LR = cv2.GaussianBlur(LR,(0,0),2);
NameError: name 'LR' is not defined

**Comment by jerofad** [comment]
@wegeneredv-de 

Add this line at line 43. `LR = cv2.resize(mat, (0,0),fx=0.5,fy=0.5)`

**Comment by danaeeeee** [comment]
@jerofad Hello， what is "mat"?I would be very appreciate it if u could tell me ,thanks！

**Comment by jerofad** [comment]
Hi @danaeeeee sorry for the late response. mat is the image matrix you want to resize
